# Generated by Django 4.1.3 on 2022-12-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="picture",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
